services:
  database:
    image: postgres:17
    container_name: paycore-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD:  ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      # Temporary, when we add the apps into compose, no need for this
      - "5432:5432" 
    volumes:
      # postgres_data is our managed mount point, cddefined outside a service
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: paycore-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
        database:
          condition: service_healthy

    # To initializr the tables of the database first
    command: >
      sh -c "alembic upgrade head &&
            uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

# Docker managed volumes are defined at root level 
volumes:
  postgres_data: