services:
  database:
    image: postgres:17
    container_name: paycore-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD:  ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # postgres_data is our managed mount point, cddefined outside a service
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: paycore-api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
        database:
          condition: service_healthy
    # To initializr the tables of the database first
    command: >
      sh -c "alembic upgrade head &&
            uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  nginx:
    image: nginx:alpine
    container_name: paycore-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api  

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: paycore-tunnel
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: >
      tunnel --no-autoupdate run
    depends_on:
      - nginx

      

 

# Docker managed volumes are defined at root level 
volumes:
  postgres_data: