"""initial

Revision ID: 2fb70e81b151
Revises: 
Create Date: 2026-06-14 10:07:02.555772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb70e81b151'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('masked_pan', sa.String(), nullable=False),
    sa.Column('currency', sa.Enum('NGN', 'USD', 'EUR', name='transaction_currency'), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processed', 'failed', 'flagged', name='transaction_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_transaction_merchant_id'), 'transaction', ['merchant_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('currency', sa.Enum('NGN', 'USD', 'EUR', name='account_currency'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.merchant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.merchant_id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ledger_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('movement_direction', sa.Enum('credit', 'debit', name='ledgermovement'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_token'], ['transaction.token'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_token')
    )
    op.create_index(op.f('ix_ledger_entry_account_id'), 'ledger_entry', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entry_account_id'), table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_table('idempotency_keys')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_index(op.f('ix_transaction_merchant_id'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
