"""added boolean column 

Revision ID: 6274ddaefbe9
Revises: 56d29107f9a5
Create Date: 2026-05-13 18:41:47.596831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6274ddaefbe9'
down_revision: Union[str, Sequence[str], None] = '56d29107f9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('bitch', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'bitch')
    # ### end Alembic commands ###
